### ISSUE TITLE
protoc-gen-fastmarshal doesn't support optional keyword of protobuf3

### ISSUE THREAD

**Issue by rohsaini** [CrowdStrike/csproto#130]
message info {
    string name = 1; // POD name
    string addr = 2; // POD IP addr
    optional uint32 data = 3;
}

xyz.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-fastmarshal hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
--fastmarshal_out:

**Comment by dylan-bourque** [comment]
Apologies for the delayed response @rohsaini but I haven't had much time to allocate to OSS lately.

You are correct that we currently don't support proto3 optional fields.  It could be added but it's not something that we (CrowdStrike) needed so it didn't make the cut.

I'd be happy to give input or review a PR if that's something you need.
