### ISSUE TITLE
Empty messages generate bad syntax

### ISSUE THREAD

**Issue by nightwolfz** [CrowdStrike/csproto#34]
## Title

Empty messages generate bad syntax

## Version

Latest

## Description

Empty messages such as
```
message WorkspaceNotFound {}
```

generate code such as
```
func (m *WorkspaceNotFound) MarshalTo(dest []byte) error {
	var (
		enc = csproto.NewEncoder(dest)
		buf []byte
		err error
	)
	_, _ = buf, err // ensure no unused variables

	return nil
}
```

Since `enc` is not used, the compilation fails.

## Repro steps

Using
--fastmarshal_out=apiversion=v2

**Comment by dylan-bourque** [comment]
Thanks for reporting this @nightwolfz. I ran into this myself and I'm already working on a fix.
