### ISSUE TITLE
float32 and double not supported?

### ISSUE THREAD

**Issue by nightwolfz** [CrowdStrike/csproto#35]
## Description

`panic(fmt.Errorf("unsupported proto kind 'double'"))`

while code is properly generated for every other type.

## Repro steps

fastmarshal_out

**Comment by dylan-bourque** [comment]
Those types should be supported and I thought I had covered them in one of the examples. I will look into it.

**Comment by dylan-bourque** [comment]
Glad to have the contribution @nightwolfz
