### ISSUE TITLE
Hide fields during marshal

### ISSUE THREAD

**Issue by kotyara85** [CrowdStrike/csproto#67]
Hello,
Does this generator supports to hide some of the fields during Marshal?
I have id field which I don't want to return to the user
Thanks

**Comment by dylan-bourque** [comment]
At this time we don't have any plans to implement this kind of feature.  Personally, I feel like this would go against the core philosophy of Protobuf anyway.  The point of Protobuf is to define the wire format of the messages.  If you don't want a particular field included there then don't include it in the Protobuf message definition.
