### ISSUE TITLE
No runtime-agnostic API for JSON marshaling

### ISSUE THREAD

**Issue by florinrm** [CrowdStrike/csproto#9]
`jsonpb.Marshaler` from `gogo/protobuf` has an `Indent` field. Example of usage:
```go
m := jsonpb.Marshaler{
    Indent: "    ",
}
```

There is no equivalent for that in `csproto` (marshalling with indent).

**Comment by dylan-bourque** [comment]
I'm thinking we should accomplish this by adding a `MarshalJSON(msg interface{}, <formatting options>) ([]byte, error)` function that delegates to the appropriate underlying runtime (Gogo/GoogleV1/GoogleV2) based on the concrete type of the passed-in message (mirroring the behavior of the existing `Marshal()` function).

The `<formatting options>` arg(s) can be either an explicit list of parameters or a struct.
